spring.application.name=ExpenseTracker
spring.datasource.url=jdbc:mysql://localhost:3306/Expense_Tracker
spring.datasource.username=root
spring.datasource.password=Naveensql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
server.port=8080